/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class su_jake_hackrf_Hackrf_RxCallback */

#ifndef _Included_su_jake_hackrf_Hackrf_RxCallback
#define _Included_su_jake_hackrf_Hackrf_RxCallback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
